import UIKit

final class ScreenshotStateViewController: UIViewController {
    private let state: String
    init(state: String) { self.state = state; super.init(nibName: nil, bundle: nil) }
    @available(*, unavailable) required init?(coder: NSCoder) { fatalError("Storyboard initialization is not supported") }

    override func viewDidLoad() {
        super.viewDidLoad(); title = screenTitle; view.backgroundColor = AppTheme.background
        let scroll = UIScrollView(); scroll.translatesAutoresizingMaskIntoConstraints = false
        let stack = UIStackView(); stack.axis = .vertical; stack.spacing = 12; stack.translatesAutoresizingMaskIntoConstraints = false
        stack.addArrangedSubview(header()); stack.addArrangedSubview(primaryCard())
        if state == "modeSelection" { addModes(to: stack) }
        else if state == "taskInput" { addTaskInput(to: stack) }
        else if state == "resultsHistory" { addResults(to: stack) }
        else if state == "phoneOtpSettings" { addSettings(to: stack) }
        else if state == "smokeTests" || state == "smokeTestResult" { addSmokeTests(to: stack) }
        else { addMetrics(to: stack); addCurrentTask(to: stack); addActivity(to: stack) }
        scroll.addSubview(stack); view.addSubview(scroll)
        NSLayoutConstraint.activate([scroll.topAnchor.constraint(equalTo: view.safeAreaLayoutGuide.topAnchor, constant: 12), scroll.leadingAnchor.constraint(equalTo: view.leadingAnchor, constant: 16), scroll.trailingAnchor.constraint(equalTo: view.trailingAnchor, constant: -16), scroll.bottomAnchor.constraint(equalTo: view.bottomAnchor), stack.topAnchor.constraint(equalTo: scroll.contentLayoutGuide.topAnchor), stack.leadingAnchor.constraint(equalTo: scroll.contentLayoutGuide.leadingAnchor), stack.trailingAnchor.constraint(equalTo: scroll.contentLayoutGuide.trailingAnchor), stack.bottomAnchor.constraint(equalTo: scroll.contentLayoutGuide.bottomAnchor), stack.widthAnchor.constraint(equalTo: scroll.frameLayoutGuide.widthAnchor)])
    }

    private var screenTitle: String { switch state { case "modeSelection": return "Choose Mode"; case "taskInput": return "New Task"; case "resultsHistory": return "Results"; case "phoneOtpSettings": return "Phone OTP"; case "smokeTests", "smokeTestResult": return "Tools"; default: return "Dashboard" } }
    private func header() -> UIView { let v = UIStackView(); v.axis = .vertical; v.spacing = 2; let name = UILabel(); name.text = "PokeTool"; name.font = .preferredFont(forTextStyle: .largeTitle); let sub = UILabel(); sub.text = "Automation control center"; sub.textColor = AppTheme.muted; v.addArrangedSubview(name); v.addArrangedSubview(sub); return v }
    private func primaryCard() -> UIView { let c = AppTheme.cardView(); c.layer.cornerRadius = 20; let s = UIStackView(); s.axis = .vertical; s.spacing = 8; s.translatesAutoresizingMaskIntoConstraints = false; let badge = UILabel(); badge.text = "  \(badgeText)  "; badge.textColor = badgeColor; badge.backgroundColor = badgeColor.withAlphaComponent(0.18); badge.font = .preferredFont(forTextStyle: .caption1); badge.layer.cornerRadius = 9; badge.clipsToBounds = true; let title = UILabel(); title.text = primaryTitle; title.font = .preferredFont(forTextStyle: .title2); let detail = UILabel(); detail.text = primaryDetail; detail.textColor = AppTheme.muted; detail.numberOfLines = 0; s.addArrangedSubview(badge); s.addArrangedSubview(title); s.addArrangedSubview(detail); if state == "dashboardRunning" || state == "phoneOtpWaiting" { let p = UIProgressView(); p.progress = 0.67; p.progressTintColor = AppTheme.accent; s.addArrangedSubview(p) }; c.addSubview(s); NSLayoutConstraint.activate([s.topAnchor.constraint(equalTo: c.topAnchor, constant: 18), s.leadingAnchor.constraint(equalTo: c.leadingAnchor, constant: 18), s.trailingAnchor.constraint(equalTo: c.trailingAnchor, constant: -18), s.bottomAnchor.constraint(equalTo: c.bottomAnchor, constant: -18)]); return c }
    private var badgeText: String { switch state { case "dashboardRunning": return "RUNNING"; case "dashboardSuccess": return "SUCCESS"; case "dashboardError": return "ERROR"; case "dashboardStopped": return "STOPPED"; case "phoneOtpWaiting": return "WAITING"; case "threeDSWaiting": return "3DS · USER ACTION"; default: return "READY" } }
    private var badgeColor: UIColor { switch state { case "dashboardRunning": return AppTheme.accent; case "dashboardSuccess": return AppTheme.success; case "dashboardError": return AppTheme.danger; case "dashboardStopped": return AppTheme.warning; case "phoneOtpWaiting": return AppTheme.warning; default: return AppTheme.accent } }
    private var primaryTitle: String { switch state { case "dashboardRunning": return "Processing tasks"; case "dashboardSuccess": return "All tasks completed"; case "dashboardError": return "Could not complete run"; case "dashboardStopped": return "Run stopped"; case "phoneOtpWaiting": return "Waiting for phone OTP"; case "threeDSWaiting": return "Complete verification in browser"; default: return "Ready to run" } }
    private var primaryDetail: String { switch state { case "dashboardRunning": return "JumpCS · DEMO_ACCOUNT_01\nProfile verification · Step 4 of 6"; case "dashboardSuccess": return "2 tasks completed successfully\nNo pending operations"; case "dashboardError": return "Network timeout handled safely\nNo secrets exposed"; case "dashboardStopped": return "Stopped by user\nCleanup completed"; case "phoneOtpWaiting": return "Gateway connected · Order DEMO-ORDER-001\nMasked phone 090-****-1234 · 00:45 elapsed"; case "threeDSWaiting": return "Your bank may ask for additional verification.\nAutomation is paused until you finish."; default: return "Choose a mode and add tasks to begin." } }
    private func addMetrics(to stack: UIStackView) { let row = UIStackView(); row.axis = .horizontal; row.spacing = 8; row.distribution = .fillEqually; ["Total\n12", "Success\n8", "Failed\n1", "Pending\n3"].forEach { t in let c = AppTheme.cardView(); let l = UILabel(); l.text = t; l.numberOfLines = 2; l.textAlignment = .center; l.font = .preferredFont(forTextStyle: .headline); l.translatesAutoresizingMaskIntoConstraints = false; c.addSubview(l); NSLayoutConstraint.activate([l.topAnchor.constraint(equalTo: c.topAnchor, constant: 12), l.leadingAnchor.constraint(equalTo: c.leadingAnchor, constant: 2), l.trailingAnchor.constraint(equalTo: c.trailingAnchor, constant: -2), l.bottomAnchor.constraint(equalTo: c.bottomAnchor, constant: -12)]); row.addArrangedSubview(c) }; stack.addArrangedSubview(row) }
    private func addCurrentTask(to stack: UIStackView) { addSection("CURRENT ACCOUNT", "DEMO_ACCOUNT_01                         1 / 12\nuser***@example.com\n\nRUNNING MODE\njumpcs.validatePhoneOtp\n\nCURRENT STEP\nPHONE OTP · Waiting for verification\n\nELAPSED                         ETA\n00:01:32                         00:00:48\n\nSPEED                           RETRIES\n38 accounts/hour                0", to: stack) }
    private func addActivity(to stack: UIStackView) { addSection("RECENT ACTIVITY", "✓ 09:42  Login verified                         SUCCESS\n● 09:41  Waiting for OTP                         WAITING\n✓ 09:40  Gateway connected                        READY\n✓ 09:39  Session prepared", to: stack); addSection("PHONE OTP GATEWAY", "CONNECTED     Mock Gateway\nORDER          DEMO-ORDER-001\nPHONE          090-****-1234\nSTATUS         Waiting for OTP · 00:45", to: stack) }
    private func addSection(_ heading: String, _ text: String, to stack: UIStackView) { let c = AppTheme.cardView(); let h = UILabel(); h.text = heading; h.font = .preferredFont(forTextStyle: .caption1); h.textColor = AppTheme.muted; let l = UILabel(); l.text = text; l.numberOfLines = 0; l.font = .preferredFont(forTextStyle: .callout); let s = UIStackView(arrangedSubviews: [h, l]); s.axis = .vertical; s.spacing = 8; s.translatesAutoresizingMaskIntoConstraints = false; c.addSubview(s); NSLayoutConstraint.activate([s.topAnchor.constraint(equalTo: c.topAnchor, constant: 16), s.leadingAnchor.constraint(equalTo: c.leadingAnchor, constant: 16), s.trailingAnchor.constraint(equalTo: c.trailingAnchor, constant: -16), s.bottomAnchor.constraint(equalTo: c.bottomAnchor, constant: -16)]); stack.addArrangedSubview(c) }
    private func addModes(to stack: UIStackView) { ["Pokémon Center|Create Account|Lottery|Check Result|Change Profile / Order|Change Email|Buy (Auto Buy)", "Jump+|Register|Login|Premium|Subscribe", "Jump Characters Store|Prepare Session|Register|Validate Phone OTP|Profile|Checkout|Buy"].forEach { group in let parts = group.split(separator: "|").map(String.init); addSection(parts[0], parts.dropFirst().map { "◉  \($0)   ›" }.joined(separator: "\n"), to: stack) } }
    private func addTaskInput(to stack: UIStackView) { addSection("TASK FORMAT", "Mode: jumpcs.validatePhoneOtp\nAccount: user***@example.com\nExpected rows: 2  ·  Valid: 2  ·  Invalid: 0", to: stack); let c = UITextView(); c.text = "DEMO_ACCOUNT_01\nuser***@example.com"; c.font = .preferredFont(forTextStyle: .body); c.isEditable = false; c.backgroundColor = AppTheme.card; c.layer.cornerRadius = 12; c.heightAnchor.constraint(equalToConstant: 150).isActive = true; stack.addArrangedSubview(c) }
    private func addResults(to stack: UIStackView) { ["SUCCESS  jumpcs.validatePhoneOtp", "STOPPED  pokemon.lottery", "ERROR  pokemon.changeEmail", "SUCCESS  jumpplus.login"].forEach { addSection($0, "DEMO_ACCOUNT_01   ·   00:01:32   ·   View details ›", to: stack) } }
    private func addSettings(to stack: UIStackView) { addSection("GATEWAY CONFIGURATION", "Gateway URL\nhttps://mock-gateway.example.com\n\nAPI Key\n••••••••••••••••\n\nTimeout  30s       Poll interval  3s\n\nCONNECTED   ·   Last checked just now", to: stack); let b = UIButton(configuration: .filled()); b.configuration?.title = "Test Connection"; stack.addArrangedSubview(b); let clear = UIButton(configuration: .tinted()); clear.configuration?.title = "Clear Configuration"; stack.addArrangedSubview(clear) }
    private func addSmokeTests(to stack: UIStackView) { ["Gateway Health", "Mock Phone OTP", "JumpCS validate phone", "STOP / cleanup", "3DS fixture", "Redaction audit"].forEach { addSection($0, state == "smokeTestResult" ? "PASS  ·  00:00:02  ·  Run again ›" : "Ready to run  ·  Run test ›", to: stack) } }
}
