"use strict";
const Pages=require("./jumpplus-pages");
const actions=require("./jumpplus-actions");
const errors=require("./jumpplus-errors");
const PREMIUM="https://shonenjumpplus.com/premium/confirm?product_id="+Pages.PRODUCT_ID;
async function premium(session,task,context){const browser=session.browser;const premiumState=await browser.evaluate(`(function(){const el=document.querySelector("li.plus-header-nav-premium.js-show-for-premium");return el&&String(el.innerText||el.textContent||"").replace(/\\s+/g,"").includes("\\u5b9a\\u671f\\u8cfc\\u8aad\\u4e2d");})()`);if(premiumState)return {status:"ALREADY_SUBSCRIBED"};await actions.open(session,"PREMIUM",PREMIUM,context);await actions.emit("jumpplus.premium.opened",task,{productId:Pages.PRODUCT_ID});return {status:"READY_FOR_PAYMENT"};}
async function openMethod(session,task,context){await Pages.assert(session.browser,"PREMIUM",{timeoutMs:5000,cancellationToken:context.cancellationToken});const clicked=await actions.clickText(session.browser,"\u6c7a\u6e08\u65b9\u6cd5\u3092\u9078\u629e\u3059\u308b",'button[type="submit"]');if(!clicked)throw errors.create("JUMPPLUS_PAYMENT_METHOD_UNAVAILABLE","Payment-method navigation was unavailable.",{step:"PAYMENT_METHOD"});await Pages.wait(session.browser,"PAYMENT_METHOD",{timeoutMs:30000,cancellationToken:context.cancellationToken});}
async function selectCredit(session,task,context){await Pages.assert(session.browser,"PAYMENT_METHOD",{timeoutMs:5000,cancellationToken:context.cancellationToken});await session.browser.click("a.payment_choose_credit_3d");await Pages.wait(session.browser,"CREDIT_FORM",{timeoutMs:30000,cancellationToken:context.cancellationToken});await actions.emit("jumpplus.payment.method.selected",task,{method:"credit3d2"});}
function normalize(payment){const value=payment||{};const cardNumber=String(value.cardNumber||"").replace(/\D/g,"");const expMonth=String(value.expMonth||"").padStart(2,"0");let expYear=String(value.expYear||"");if(expYear.length===2)expYear="20"+expYear;const securityCode=String(value.securityCode||value.cvv||"").replace(/\D/g,"");if(cardNumber.length<13||cardNumber.length>19||Number(expMonth)<1||Number(expMonth)>12||!/^\d{4}$/.test(expYear)||securityCode.length<3||securityCode.length>4)throw errors.create("JUMPPLUS_PAYMENT_VALIDATION_FAILED","Transient card fields failed local validation.",{step:"CREDIT_FORM"});return {cardNumber,expMonth,expYear,securityCode};}
async function fill(session,task,context){await Pages.assert(session.browser,"CREDIT_FORM",{timeoutMs:5000,cancellationToken:context.cancellationToken});const payment=normalize(task.input.payment);const browser=session.browser;await actions.setVerified(browser,'input[name="ccNumber"]',payment.cardNumber,true);await browser.selectValue('select[name="ccExpirationMonth"]',payment.expMonth);await browser.selectValue('select[name="ccExpirationYear"]',payment.expYear);await actions.setVerified(browser,'input[name="securityCode"]',payment.securityCode,true);const lengths=await browser.evaluate(`(function(){const n=document.querySelector('input[name="ccNumber"]'),c=document.querySelector('input[name="securityCode"]');return {cardDigits:String(n&&n.value||"").replace(/\\D/g,"").length,securityDigits:String(c&&c.value||"").replace(/\\D/g,"").length};})()`);if(!lengths||lengths.cardDigits!==payment.cardNumber.length||lengths.securityDigits!==payment.securityCode.length)throw errors.create("JUMPPLUS_PAYMENT_VALIDATION_FAILED","Credit fields could not be safely verified.",{step:"CREDIT_FORM"});await actions.emit("jumpplus.payment.form.ready",task);return {method:"credit3d2"};}
async function review(session,task,context){await Pages.assert(session.browser,"CREDIT_FORM",{timeoutMs:5000,cancellationToken:context.cancellationToken});const clicked=await actions.clickText(session.browser,"\u6b21\u3078",'form[name="creditFepChargePaymentInfoEntryActionForm"] a.common-button');if(!clicked)throw errors.create("JUMPPLUS_PAYMENT_VALIDATION_FAILED","Credit form next action was unavailable.",{step:"CREDIT_SUBMIT"});try{const result=await Pages.wait(session.browser,"REVIEW",{timeoutMs:30000,cancellationToken:context.cancellationToken});session.record(result);await actions.emit("jumpplus.payment.review.ready",task,{productId:Pages.PRODUCT_ID});return result;}catch(cause){const text=await session.browser.text();if(/\u30ab\u30fc\u30c9.*\u5229\u7528\u3067\u304d|\u6c7a\u6e08.*\u5931\u6557/.test(text))throw errors.create("JUMPPLUS_PAYMENT_REJECTED","Jump Plus rejected payment details.",{step:"CREDIT_SUBMIT"},cause);throw errors.create("JUMPPLUS_REVIEW_PAGE_MISMATCH","Payment review was not verified; form will not be resubmitted.",{step:"CREDIT_SUBMIT"},cause);}}
async function finalSubmit(session,task,context){if(!task.options.allowFinalSubmit)return {status:"READY_FOR_FINAL_SUBMIT",data:{productId:Pages.PRODUCT_ID,paymentMethod:"credit3d2"}};await Pages.assert(session.browser,"REVIEW",{timeoutMs:5000,cancellationToken:context.cancellationToken});await actions.emit("jumpplus.subscription.finalSubmit",task,{productId:Pages.PRODUCT_ID,irreversible:true});const clicked=await actions.clickText(session.browser,"\u8cfc\u5165",'form[name="fepChargeIntensionConfirmActionForm"] a.common-button');if(!clicked)throw errors.create("JUMPPLUS_SUBSCRIPTION_FAILED","Final purchase action was unavailable.",{step:"FINAL_SUBMIT"});const deadline=performance.now()+120000;while(performance.now()<deadline){actions.cancel(context);try{const done=await Pages.inspect(session.browser,Pages.pages.COMPLETE);if(done.ok){await actions.emit("jumpplus.subscription.completed",task,{productId:Pages.PRODUCT_ID});return {status:"SUBSCRIBED",data:{productId:Pages.PRODUCT_ID}};}}catch(_){}try{const threeDS=await Pages.inspect(session.browser,Pages.pages.THREEDS);if(threeDS.ok){await actions.emit("jumpplus.3ds.required",task);return {status:"WAITING_FOR_3DS_USER_ACTION",code:"JUMPPLUS_3DS_REQUIRED",data:{productId:Pages.PRODUCT_ID}};}}catch(_){}const text=await session.browser.text();if(/\u6c7a\u6e08.*\u5931\u6557|\u30ab\u30fc\u30c9.*\u5229\u7528\u3067\u304d/.test(text))return {status:"PAYMENT_REJECTED",code:"JUMPPLUS_PAYMENT_REJECTED",data:{productId:Pages.PRODUCT_ID}};await PokeToolRuntime.web.delay(250);}throw errors.create("JUMPPLUS_SUBSCRIPTION_STATE_UNKNOWN","Final subscription outcome is unknown and will not be submitted again.",{step:"FINAL_SUBMIT"});}
module.exports={PREMIUM,normalize,premium,openMethod,selectCredit,fill,review,finalSubmit};
