"use strict";
const CODES=Object.freeze([
"JUMPPLUS_INVALID_TASK","JUMPPLUS_HOME_PAGE_MISMATCH","JUMPPLUS_LOGIN_POPUP_NOT_FOUND",
"JUMPPLUS_SIGNUP_FORM_NOT_FOUND","JUMPPLUS_SIGNUP_VALIDATION_FAILED","JUMPPLUS_SIGNUP_SUBMIT_FAILED",
"JUMPPLUS_SIGNUP_STATE_UNKNOWN","JUMPPLUS_ACCOUNT_ALREADY_EXISTS","JUMPPLUS_CONFIRMATION_MAIL_TIMEOUT",
"JUMPPLUS_CONFIRMATION_URL_INVALID","JUMPPLUS_CONFIRMATION_TOKEN_EXPIRED","JUMPPLUS_CONFIRMATION_FAILED",
"JUMPPLUS_INVALID_CREDENTIAL","JUMPPLUS_ACCOUNT_NOT_CONFIRMED","JUMPPLUS_LOGIN_FAILED",
"JUMPPLUS_ACCOUNT_NOT_READY","JUMPPLUS_PREMIUM_PAGE_MISMATCH","JUMPPLUS_PREMIUM_PRODUCT_UNAVAILABLE",
"JUMPPLUS_ALREADY_SUBSCRIBED","JUMPPLUS_PAYMENT_METHOD_UNAVAILABLE","JUMPPLUS_CREDIT_FORM_MISMATCH",
"JUMPPLUS_PAYMENT_VALIDATION_FAILED","JUMPPLUS_PAYMENT_REJECTED","JUMPPLUS_REVIEW_PAGE_MISMATCH",
"JUMPPLUS_FINAL_SUBMIT_DISABLED","JUMPPLUS_3DS_REQUIRED","JUMPPLUS_3DS_FAILED",
"JUMPPLUS_SUBSCRIPTION_FAILED","JUMPPLUS_SUBSCRIPTION_STATE_UNKNOWN","JUMPPLUS_CAPTCHA_REQUIRED",
"JUMPPLUS_RATE_LIMITED","JUMPPLUS_MAINTENANCE","JUMPPLUS_ACCESS_DENIED",
"JUMPPLUS_SESSION_EXPIRED","JUMPPLUS_PAGE_MISMATCH","JUMPPLUS_UNEXPECTED_PAGE",
"JUMPPLUS_RETRY_EXHAUSTED","JUMPPLUS_CANCELLED","JUMPPLUS_RUNTIME_STOPPED","JUMPPLUS_INTERNAL_ERROR"]);
function create(code,message,context,cause){const error=new Error(message);error.name="JumpPlusError";error.code=CODES.includes(code)?code:"JUMPPLUS_INTERNAL_ERROR";error.step=context&&context.step||null;error.retryable=Boolean(context&&context.retryable);error.causeCode=cause&&cause.code||null;error.diagnostics=context&&context.diagnostics||null;return error;}
function wrap(error,context){if(error&&error.name==="JumpPlusError")return error;if(error&&["TASK_CANCELLED","OPERATION_CANCELLED","CANCELLED"].includes(error.code))return create("JUMPPLUS_CANCELLED","Jump Plus task was cancelled.",context,error);return create("JUMPPLUS_INTERNAL_ERROR",error&&error.message||"Jump Plus operation failed.",context,error);}
module.exports={CODES,create,wrap};
