"use strict";
const Pages=require("./jumpplus-pages");
const actions=require("./jumpplus-actions");
const Confirmation=require("./jumpplus-email-confirmation");
const errors=require("./jumpplus-errors");
async function openLoginPopup(session,task,context){const browser=session.browser;const current=await Pages.identify(browser);if(current.page==="LOGIN_POPUP")return {state:"ALREADY_OPEN"};await Pages.assert(browser,"HOME",{timeoutMs:10000,cancellationToken:context.cancellationToken});let clicked=await actions.clickText(browser,"\u30ed\u30b0\u30a4\u30f3\u65b0\u898f\u767b\u9332");if(!clicked)clicked=await actions.clickText(browser,"\u30ed\u30b0\u30a4\u30f3\uff0f\u65b0\u898f\u767b\u9332");if(!clicked)clicked=await actions.clickText(browser,"\u30ed\u30b0\u30a4\u30f3");if(!clicked)throw errors.create("JUMPPLUS_LOGIN_POPUP_NOT_FOUND","Visible login trigger was not found.",{step:"OPEN_LOGIN"});await Pages.wait(browser,"LOGIN_POPUP",{timeoutMs:15000,cancellationToken:context.cancellationToken});await actions.emit("jumpplus.login.opened",task);return {state:"OPENED"};}
async function openSignup(session,task,context){await Pages.assert(session.browser,"LOGIN_POPUP",{timeoutMs:5000,cancellationToken:context.cancellationToken});await session.browser.click("button.js-signup-button");await Pages.wait(session.browser,"SIGNUP_FORM",{timeoutMs:15000,cancellationToken:context.cancellationToken});await actions.emit("jumpplus.signup.opened",task);}
async function fill(session,task){const browser=session.browser;const form='form:has(#input-agreement) ';await actions.setVerified(browser,form+'input[name="email_address"]',task.account.email,false);await actions.setVerified(browser,form+'input[name="password"]',task.account.password,true);await browser.setChecked("#input-agreement",true);const checked=await browser.query("#input-agreement","checked");if(!checked)throw errors.create("JUMPPLUS_SIGNUP_VALIDATION_FAILED","Agreement checkbox was not checked.",{step:"SIGNUP_FILL"});return {emailMatches:true,passwordLength:task.account.password.length,agreement:true};}
async function state(browser){return browser.evaluate(`(function(){const text=String(document.body&&document.body.innerText||"");const alerts=Array.from(document.querySelectorAll(".error-message,[role=alert]")).filter(function(el){const r=el.getBoundingClientRect(),s=getComputedStyle(el);return r.width>0&&r.height>0&&s.display!=="none"&&s.visibility!=="hidden";}).map(function(el){return String(el.innerText||el.textContent||"");});return {mailSent:text.includes("\\u767b\\u9332\\u30e1\\u30fc\\u30eb\\u3092\\u9001\\u4fe1\\u3057\\u307e\\u3057\\u305f"),duplicate:/\\u767b\\u9332\\u6e08|\\u65e2\\u306b\\u767b\\u9332|\\u4f7f\\u7528\\u3055\\u308c\\u3066\\u3044\\u307e\\u3059/.test(text),validation:alerts.length?alerts:null};})()`);}
async function submit(session,task,context){await Pages.assert(session.browser,"SIGNUP_FORM",{timeoutMs:5000,cancellationToken:context.cancellationToken});const notBefore=Date.now();const clicked=await actions.clickText(session.browser,"\u65b0\u898f\u4f1a\u54e1\u767b\u9332",'form:has(#input-agreement) button[type="submit"]');if(!clicked)throw errors.create("JUMPPLUS_SIGNUP_SUBMIT_FAILED","Signup submit button was not found.",{step:"SIGNUP_SUBMIT"});await actions.emit("jumpplus.signup.submitted",task);const deadline=performance.now()+20000;while(performance.now()<deadline){actions.cancel(context);const current=await state(session.browser);if(current.mailSent)return {state:"MAIL_SENT",notBefore};if(current.duplicate)return {state:"ACCOUNT_ALREADY_EXISTS",notBefore};if(current.validation)throw errors.create("JUMPPLUS_SIGNUP_VALIDATION_FAILED","Jump Plus rejected signup form values.",{step:"SIGNUP_SUBMIT"});await PokeToolRuntime.web.delay(250);}throw errors.create("JUMPPLUS_SIGNUP_STATE_UNKNOWN","Signup outcome is unknown; submit will not be repeated.",{step:"SIGNUP_SUBMIT"});}
async function confirm(session,task,context,notBefore){await actions.emit("jumpplus.confirmation.waiting",task);const link=await Confirmation.wait(task,context,notBefore);await actions.emit("jumpplus.confirmation.received",task,{source:link.source});await session.browser.load(link.value);try{const result=await Pages.wait(session.browser,"CONFIRMATION",{timeoutMs:30000,cancellationToken:context.cancellationToken});session.record(result);await actions.emit("jumpplus.account.confirmed",task);return {status:"ACCOUNT_CONFIRMED"};}catch(error){const text=await session.browser.text();if(/\u671f\u9650.*\u5207|\u7121\u52b9/.test(text))throw errors.create("JUMPPLUS_CONFIRMATION_TOKEN_EXPIRED","Confirmation token is expired or invalid.",{step:"CONFIRMATION"},error);throw errors.create("JUMPPLUS_CONFIRMATION_FAILED","Confirmation destination was not verified.",{step:"CONFIRMATION"},error);}}
async function register(session,task,context){await openLoginPopup(session,task,context);await openSignup(session,task,context);await fill(session,task);const submitted=await submit(session,task,context);if(submitted.state==="ACCOUNT_ALREADY_EXISTS"){if(task.options.allowExistingAccount)return {status:"ACCOUNT_ALREADY_EXISTS",existing:true};throw errors.create("JUMPPLUS_ACCOUNT_ALREADY_EXISTS","Jump Plus account already exists.",{step:"SIGNUP_SUBMIT"});}await confirm(session,task,context,submitted.notBefore);return {status:"ACCOUNT_CREATED",existing:false};}
module.exports={openLoginPopup,openSignup,fill,state,submit,confirm,register};
