"use strict";
const MODES=Object.freeze({Create:"confirmationURL",ChangeEmail:"confirmationURL",CheckMail:"resultBatch",Lottery:"numericOTP",CheckResult:"numericOTP",ChangeProfileOrder:"numericOTP",Buy:"numericOTP"});
function normalize(value){return String(value||"").replace(/&amp;/gi,"&").replace(/&nbsp;/gi," ").replace(/<br\s*\/?>/gi,"\n").replace(/<[^>]+>/g," ").replace(/\r/g,"");}
function providerHost(email,customHosts){const address=String(email||"").trim().toLowerCase();const domain=address.split("@").pop();if(!address.includes("@")||!domain)return null;if(domain==="gmail.com")return "imap.gmail.com";if(["icloud.com","me.com","mac.com"].includes(domain))return "imap.mail.me.com";const configured=customHosts&&customHosts[domain];return typeof configured==="string"&&configured?configured:null;}
function extractNumericOTP(text){const value=normalize(text);const labelled=value.match(/(?:\u3010\u30d1\u30b9\u30b3\u30fc\u30c9\u3011|\u30d1\u30b9\u30b3\u30fc\u30c9|\u8a8d\u8a3c\u30b3\u30fc\u30c9|\u78ba\u8a8d\u30b3\u30fc\u30c9)\s*[:\uff1a]?\s*(\d{6})/i);if(labelled)return labelled[1];const fallback=value.match(/\b(\d{6})\b/);return fallback?fallback[1]:null;}
function extractConfirmationURL(text,mode){const value=normalize(text);const pattern=mode==="Create"?/https:\/\/www\.pokemoncenter-online\.com\/new-customer\/\?token=[^\s"'<>]+/i:/https:\/\/www\.pokemoncenter-online\.com\/mail-change-complete\/\?token=[^\s"'<>]+/i;const match=value.match(pattern);return match?match[0].trim():null;}
function classifyLotteryMail(mail,productId){const subject=String(mail&&mail.subject||"");const body=normalize(`${subject}\n${mail&&mail.text||""}\n${mail&&mail.html||""}`);const brand="\u300c\u30dd\u30b1\u30e2\u30f3\u30bb\u30f3\u30bf\u30fc\u30aa\u30f3\u30e9\u30a4\u30f3\u300d";const supported=subject.includes("\u5f53\u9078\u306e\u3054\u6848\u5185"+brand)||subject.includes("\u62bd\u9078\u7d50\u679c\u306e\u3054\u6848\u5185"+brand);if(!supported||(productId&&!body.includes(String(productId))))return null;if(body.includes("\u5f53\u9078"))return "WON";if(body.includes("\u843d\u9078"))return "LOST";return "PENDING";}
function parseMail(mail,mode){const content=`${mail&&mail.subject||""}\n${mail&&mail.text||""}\n${mail&&mail.html||""}`;if(mode==="Create"&&String(mail&&mail.subject||"").includes("\u30e1\u30fc\u30eb\u30a2\u30c9\u30ec\u30b9\u306f\u65e2\u306b\u767b\u9332\u6e08\u307f\u3067\u3059"))return {type:"alreadyRegistered",value:"REGISTERED_MAIL"};if(MODES[mode]==="confirmationURL"){const value=extractConfirmationURL(content,mode);return value?{type:"confirmationURL",value}:null;}const value=extractNumericOTP(content);return value?{type:"numericOTP",value}:null;}
function matchesEnvelope(mail,request){const timestamp=new Date(mail&&(mail.date||mail.receivedDate)||0).getTime();if(Number(request.receivedAfter||0)&&(!Number.isFinite(timestamp)||timestamp<Number(request.receivedAfter)))return false;const recipient=String(mail&&mail.to&&mail.to.text||"").toLowerCase();if(!recipient.includes(String(request.targetEmail||"").toLowerCase()))return false;if(request.sender&&!String(mail&&mail.from&&mail.from.text||"").toLowerCase().includes(String(request.sender).toLowerCase()))return false;return true;}
module.exports={MODES,normalize,providerHost,extractNumericOTP,extractConfirmationURL,classifyLotteryMail,parseMail,matchesEnvelope};
